@host = localhost:9001

### Get All Material
GET http://{{host}}/material 

### Get Specific Material
GET http://{{host}}/material/MAT001

### Get Packaging Material
GET http://{{host}}/material?grp=Packaging

### Get Raw Material
GET http://{{host}}/material?grp=RAW Material



### Create New Material
POST http://{{host}}/material
Content-Type: application/json

{
  "code": "MAT003",
  "desc": "Material 003",
  "uom": "PC",
  "group": "Packaging"
}



### Update Material
PUT http://{{host}}/material/MAT003
Content-Type: application/json

{
  "desc": "Material 003-A",
  "uom": "KG",
  "group": "Packaging"
}


### Release/Unrelease Material
PATCH http://{{host}}/material/MAT003/release 
Content-Type: application/json

{
  "release": true
}


### Delete Material
DELETE http://{{host}}/material/MAT003
